# docker-compose.yml
version: '3.8'

services:
  cashpe:
    build: 
      context: .
      dockerfile: Dockerfile
    hostname: cashpe
    platform: linux/amd64
    container_name: cashpe
    image: cashpe:latest
    ports:
      - 8000:8000
    volumes:
      - .:/app

  postgres:
    image: postgres:15
    container_name: postgres
    hostname: postgres
    platform: linux/amd64
    environment:
      POSTGRES_DB : local_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - .:/data